version: '2'
services:
  coordinator-agent:
    build: ./components/coordinator-agent
    environment:
      - REDIS_HOST=redis:6379

  page-analyzer:
    build: ./components/page-analyzer
    environment:
      - SERVICE_PORT=9000
      - LOGGING_LEVEL=20 # this is standard Python logging mapping, 20 = INFO
    ports:
      - "9000:9000"

  flower:
    build: ./deployment/flower
    environment:
      - BROKER_URL=amqp://guest:guest@rabbitmq:5672//
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - REDIS_HOST=redis:6379
    ports:
      - "5555:5555"

  rabbitmq:
    image: rabbitmq:3.7.8-management-alpine
    ports:
      - "15672:15672"
      - "5672:5672"

  redis:
    image: redis:5.0.3-alpine
    ports:
      - "6379:6379"

  mongo:
    image: mongo
    ports:
      - "27017:27017"
