version: '2.1'
services:
  coordinator-agent:
    build: ./components/coordinator-agent
    environment:
      - RABBITMQ_HOST=guest:guest@rabbitmq:5672
      - LOGGING_LEVEL=20 # this is standard Python logging mapping, 20 = INFO
    depends_on:
      rabbitmq:
        condition: service_healthy

  page-analyzer:
    build: ./components/page-analyzer
    environment:
      - SERVICE_PORT=9000
      - LOGGING_LEVEL=20 # this is standard Python logging mapping, 20 = INFO
    ports:
      - "9000:9000"
    volumes:
      - ./components/page-analyzer/src/data:/app/src/data

  form-expert:
    build: ./components/form-expert
    environment:
      - SERVICE_PORT=9003
      - FORM_EXPERT_MONGO_URI=mongodb://mongo:27017
      - LOGGING_LEVEL=20 # this is standard Python logging mapping, 20 = INFO
    ports:
      - "9003:9003"
    healthcheck:
      test: curl --fail -s http://localhost:9003/api/v1/health_check || exit 1
      interval: 5s
      timeout: 5s
      retries: 10
    depends_on:
      - mongo

  seeding:
    build: ./seeding
    environment:
      - FORM_EXPERT_URL=http://form-expert:9003
      - LOGGING_LEVEL=20 # this is standard Python logging mapping, 20 = INFO
    depends_on:
      form-expert:
        condition: service_healthy

  flow-generator:
    build: ./components/flow-generator
    environment:
      - SERVICE_PORT=9001
      - LOGGING_LEVEL=20 # this is standard Python logging mapping, 20 = INFO
    ports:
      - "9001:9001"

  pet-clinic:
    image: jbrisbin/spring-petclinic
    ports:
      - "8080:8080"
    logging:
      driver: none

  gateway:
    build: ./components/gateway
    environment:
      - SERVICE_PORT=9002
      - RABBITMQ_HOST=guest:guest@rabbitmq:5672
      - LOGGING_LEVEL=20 # this is standard Python logging mapping, 20 = INFO
    ports:
      - "9002:9002"

  flower:
    build: ./deployment/flower
    environment:
      - RABBITMQ_HOST=guest:guest@rabbitmq:5672
      - LOGGING_LEVEL=20 # this is standard Python logging mapping, 20 = INFO
    ports:
      - "5555:5555"
    depends_on:
      rabbitmq:
        condition: service_healthy

  rabbitmq:
    image: rabbitmq:3.7.8-management-alpine
    ports:
      - "15672:15672"
      - "5672:5672"
    healthcheck:
      timeout: 5s
      interval: 5s
      retries: 15
      test:
        - "CMD"
        - "rabbitmqctl"
        - "status"
    logging:
      driver: none

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    logging:
      driver: none

  exp-test-agent-1:
    build: ./components/exp-test-agent
    environment:
      - RABBITMQ_HOST=guest:guest@rabbitmq:5672
      - RUNNER_URL=http://aeon-runner-1:8080
      - PAGE_ANALYSIS_URL=http://page-analyzer:9000
      - FLOW_GENERATION_URL=http://flow-generator:9001
      - FORM_EXPERT_URL=http://form-expert:9003
      - LOGGING_LEVEL=20 # this is standard Python logging mapping, 20 = INFO
    depends_on:
      rabbitmq:
        condition: service_healthy

  exp-test-agent-2:
    build: ./components/exp-test-agent
    environment:
      - RABBITMQ_HOST=guest:guest@rabbitmq:5672
      - RUNNER_URL=http://aeon-runner-2:8080
      - PAGE_ANALYSIS_URL=http://page-analyzer:9000
      - FLOW_GENERATION_URL=http://flow-generator:9001
      - FORM_EXPERT_URL=http://form-expert:9003
      - LOGGING_LEVEL=20 # this is standard Python logging mapping, 20 = INFO
    depends_on:
      rabbitmq:
        condition: service_healthy

  aeon-runner-1:
    image: aista/aeon-runner
    ports:
      - "8001:8080"

  aeon-runner-2:
    image: aista/aeon-runner
    ports:
      - "8002:8080"
