version: '2.1'

services:
  form-expert:
    build: ./
    ports:
      - "9003:9003"
    environment:
      - SERVICE_PORT=9003
      - FORM_EXPERT_MONGO_URI=mongodb://mongo:27017
      - LOGGING_LEVEL =20
    healthcheck:
      test: curl --fail -s http://localhost:9003/api/v1/health_check || exit 1
      interval: 5s
      timeout: 5s
      retries: 3
    depends_on:
      - mongo
      
  mongo:
    image: 'mongo'
    ports:
      - "27017:27017"
    volumes:
      - data/form-expert