version: '2'

services:
  form-expert:
    build: ./
    ports:
      - "8080:80"
    environment:
      - SERVICE_PORT=80
      - FORM_EXPERT_MONGO_URI=mongodb://mongo:27017
      
  mongo:
    image: 'mongo'
    ports:
      - "27017:27017"
    volumes:
      - data/form-expert